#!/bin/bash
source /etc/os-release
hostname=$(hostname)
username=$(whoami)
datetime=$(date)
os=$PRETTY_NAME
uptime_info=$(uptime -p)
cpu=$(lshw -class processor 2>/dev/null | grep "product:" | head -n1 | cut -d: -f2 | sed 's/^ *//')
ram=$(free -h | grep "Mem:" | awk '{print $2}')
disks=$(lshw -class disk 2>/dev/null | grep -E "product:|size:" | paste -sd " " -)
video=$(lshw -class display 2>/dev/null | grep "product:" | head -n1 | cut -d: -f2 | sed 's/^ *//')
interface=$(ip r | grep default | awk '{print $5}')
host_address=$(ip a show "$interface" | grep "inet " | awk '{print $2}' | cut -d/ -f1)
gateway=$(ip r | grep default | awk '{print $3}')
dns=$(grep nameserver /etc/resolv.conf | head -n1 | awk '{print $2}')
users=$(who | awk '{print $1}' | paste -sd "," -)
disk_space=$(df -h | awk 'NR>1 {print $6 " " $4}' | paste -sd "," -)
process_count=$(ps -e | wc -l)
load_average=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ *//')
ports=$(ss -tuln | awk 'NR>1 {print $5}' | sed 's/.*://' | sort -n -u | paste -sd "," -)
ufw_status=$(sudo ufw status 2>/dev/null | grep Status | cut -d: -f2 | sed 's/^ *//')
cat <<EOF
System Report for $hostname generated by $username, on $datetime
System Information
------------------
OS: $os
Uptime: $uptime_info
CPU: $cpu
RAM: $ram
Disk(s): $disks
Video: $video
Host Address: $host_address
Gateway IP: $gateway
DNS Server: $dns
System Status
-------------
Users Logged In: $users
Disk Space: $disk_space
Process Count: $process_count
Load Averages: $load_average
Listening Network Ports: $ports
UFW Status: $ufw_status
EOF
